---
title: Boom-HS Starting Page
---

## About this tutorial

This is intended as a short and simple way for someone who has a bit of programming experience^[Mostly made for people doing the AI course at Jönköpings Tekniska Högskola (JTH).] to start at the *right end* of learning Haskell.^[There's way too many "What is a Monad?" tutorials out there. Don't even fuck around with those for your first month. It will be a huge waste of your time.]

To reach basic proficiency you will need to master three things.

  1. The basic syntax of lists and datatypes.
  2. Understanding and writing function type signatures.
  3. Some/most of the functions in `Prelude.hs`.

This tutorial aims to guide you through these with minimal effort.


## Install GHC

If you have a package manager, preferably use that. It's around 500 MB. The package name is usually just `ghc`.

If you don't have one use [Stack](https://docs.haskellstack.org/en/stable/) but that'll take almost 2 GB.

If you're on Windows then you shouldn't be using this tutorial. You're too far outside the programmer culture in general for this to help you. Is there any real chance for you to save your soul? Repent and better your ways.^[Stack has instructions for Windows as well.]



